apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: radiantone-admin
  #namespace: 205150-isrm-vds-qa
rules:
###### Kubectl EXEC Permission########
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
    - exec
    resourceNames:
    - {{ template "zookeeper.fullname". }}-0
    - {{ template "zookeeper.fullname". }}-1
    - {{ template "zookeeper.fullname". }}-2
########Kubectl scale Permission for Rollback jobs########
  - apiGroups:
    - "apps"
    resources:
    - statefulsets/scale
    - statefulsets
    verbs:
    - get
    - list
    - watch
    - patch
    - update
    resourceNames:
    - {{ template "zookeeper.fullname". }}
###############Kubectl list Pod###################
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    verbs:
    - get
    - list
    - wait
    - watch
 ###############Kubectl delete Pod###################
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - delete
    - deletecollection
    resourceNames:
    - {{ template "zookeeper.fullname" . }}-0
    - {{ template "zookeeper.fullname" . }}-1
    - {{ template "zookeeper.fullname" . }}-2
    




