---
app: fid-helm
auto_deploy: true
context: release-customer-us-west-2
domain: fid-helm.rls.sh
mode: development
repo_name: radiantlogic-devops/release-fid
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 4Gi
    requests: 2Gi
  replicas: 1
charts:
- name: zookeeper
  directory: charts/zookeeper
  values: values.yaml
- name: fid
  directory: charts/fid
  values: values.yaml
workflows:
- name: setup
  parallelize:
  - step: radiantone
    tasks:
    - charts.zookeeper
    - charts.fid
- name: patch
  parallelize:
  - step: radiantone
    tasks:
    - charts.zookeeper
    - charts.fid
